### ISSUE TITLE
Deploy Error - Vercel Platform 

### ISSUE THREAD

**Issue by aryasoni98** [aryasoni98/Codeless-Builder#2]
![Screenshot 2022-11-26 at 3 47 09 PM](https://user-images.githubusercontent.com/18515597/204083787-0d4a31ad-754c-4ead-bac2-12a7901fd38c.png)

**Comment by itz-deepak** [comment]
assign this to me @aryasoni98

**Comment by aryasoni98** [comment]
Done ✅
